import { getChatGPTUser } from '@/app/chatgpt-auth';
import { database } from '@/db/raw';
import { stateSchema } from '@/lib/payroll/validation';
import { initialState, calculate, ENGINE } from '@/lib/payroll/engine';
export const dynamic='force-dynamic';
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store, private','X-Content-Type-Options':'nosniff'}});
const hash=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');
export async function GET(req:Request){try{const user=await getChatGPTUser();if(!user)return json({error:'Entre para acessar os dados.'},401);const db=database(),q=new URL(req.url).searchParams,id=q.get('company');if(!id){const list=await db.prepare('SELECT c.id,c.state,m.role FROM companies c JOIN members m ON c.id=m.company WHERE m.user=?').bind(user.userId).all();return json({companies:list.results.map((r:any)=>({id:r.id,name:JSON.parse(r.state).company,role:r.role}))});}const member=await db.prepare('SELECT role FROM members WHERE company=? AND user=?').bind(id,user.userId).first();if(!member)return json({error:'Você não tem acesso a esta empresa.'},403);const company=await db.prepare('SELECT state,version FROM companies WHERE id=?').bind(id).first<any>();if(q.has('history')){const result=await db.prepare('SELECT id,version,actor,reason,created FROM history WHERE company=? ORDER BY version DESC LIMIT 100').bind(id).all();return json({history:result.results});}if(q.has('snapshot')){const row=await db.prepare('SELECT snapshot FROM history WHERE company=? AND id=?').bind(id,q.get('snapshot')).first<any>();return row?json({state:JSON.parse(row.snapshot)}):json({error:'Versão não encontrada.'},404);}const members=await db.prepare('SELECT user,email,role FROM members WHERE company=?').bind(id).all();return json({state:JSON.parse(company.state),version:company.version,role:member.role,members:members.results});}catch{return json({error:'Não foi possível carregar os dados. Tente novamente.'},503);}}
export async function POST(req:Request){try{const user=await getChatGPTUser();if(!user)return json({error:'Entre para salvar os dados.'},401);const origin=req.headers.get('origin');if(!origin||origin!==new URL(req.url).origin||req.headers.get('x-sol-request')!=='1')return json({error:'Origem da solicitação inválida.'},403);if(!req.headers.get('content-type')?.startsWith('application/json'))return json({error:'Formato inválido.'},415);const raw=await req.text();if(raw.length>1500000)return json({error:'Arquivo muito grande. Limite de 1,5 MB.'},413);const body=JSON.parse(raw),db=database(),now=new Date().toISOString();if(body.action==='create'){const count=await db.prepare('SELECT COUNT(*) AS n FROM members WHERE user=? AND role=?').bind(user.userId,'admin').first<any>();if(count.n>=20)return json({error:'Limite de 20 empresas por administrador.'},400);const id=crypto.randomUUID(),state=initialState();state.company=typeof body.name==='string'?body.name:state.company;stateSchema.parse(state);await db.batch([db.prepare('INSERT INTO companies (id,state,version,op) VALUES (?,?,0,?)').bind(id,JSON.stringify(state),id),db.prepare('INSERT INTO members (company,user,email,role) VALUES (?,?,?,?)').bind(id,user.userId,user.email,'admin'),db.prepare('INSERT INTO history (id,company,version,actor,reason,created,snapshot) VALUES (?,?,0,?,?,?,?)').bind(crypto.randomUUID(),id,user.email,'Empresa criada',now,JSON.stringify({...state,calculationVersion:ENGINE,results:[]}))]);return json({id});}
if(body.action==='accept'){if(typeof body.token!=='string'||body.token.length>100)return json({error:'Código inválido.'},400);const h=await hash(body.token);const invite=await db.prepare('SELECT company FROM invites WHERE hash=? AND used IS NULL AND expires>? AND recipient=?').bind(h,now,user.email.toLowerCase()).first<any>();if(!invite)return json({error:'Convite expirado, utilizado ou destinado a outro e-mail.'},400);const existing=await db.prepare('SELECT role FROM members WHERE company=? AND user=?').bind(invite.company,user.userId).first();if(existing)return json({id:invite.company});const result=await db.batch([db.prepare('INSERT INTO members (company,user,email,role) SELECT company,?,?,? FROM invites WHERE hash=? AND used IS NULL AND expires>? AND recipient=?').bind(user.userId,user.email,'contador',h,now,user.email.toLowerCase()),db.prepare('UPDATE invites SET used=? WHERE hash=? AND used IS NULL AND recipient=?').bind(user.userId,h,user.email.toLowerCase())]);if(!result[0].meta.changes)return json({error:'Convite indisponível.'},409);return json({id:invite.company});}
const id=body.company;if(typeof id!=='string')return json({error:'Empresa inválida.'},400);const member=await db.prepare('SELECT role FROM members WHERE company=? AND user=?').bind(id,user.userId).first<any>();if(!member)return json({error:'Acesso não autorizado.'},403);
if(body.action==='invite'){if(member.role!=='admin')return json({error:'Apenas o administrador pode convidar.'},403);if(typeof body.email!=='string'||!/^\S+@\S+\.\S+$/.test(body.email)||body.email.length>200)return json({error:'Informe o e-mail do contador.'},400);const token=crypto.randomUUID()+crypto.randomUUID();await db.prepare('INSERT INTO invites (hash,company,expires,recipient) VALUES (?,?,?,?)').bind(await hash(token),id,new Date(Date.now()+7*86400000).toISOString(),body.email.trim().toLowerCase()).run();return json({token});}
if(body.action==='revoke'){if(member.role!=='admin'||typeof body.user!=='string')return json({error:'Apenas o administrador pode remover acessos.'},403);await db.batch([db.prepare('DELETE FROM members WHERE company=? AND user=? AND role<>?').bind(id,body.user,'admin'),db.prepare('DELETE FROM invites WHERE company=?').bind(id)]);return json({ok:true});}
if(body.action!=='save')return json({error:'Ação inválida.'},400);if(!Number.isInteger(body.version)||typeof body.reason!=='string'||body.reason.trim().length<5||body.reason.length>500)return json({error:'Informe uma justificativa com 5 a 500 caracteres.'},400);const state=stateSchema.parse(body.state);const current=await db.prepare('SELECT state FROM companies WHERE id=?').bind(id).first<any>();const previous=JSON.parse(current.state);if(member.role!=='admin'&&['company','city','uf','convention'].some(k=>(state as any)[k]!==previous[k]))return json({error:'Somente o administrador altera as configurações da empresa.'},403);for(const e of previous.entries){const next=state.entries.find(x=>x.id===e.id);if(!next||JSON.stringify(next.original)!==JSON.stringify(e.original))return json({error:'O registro original deve ser preservado. Corrija os lançamentos existentes.'},400);}const op=crypto.randomUUID(),revision=body.version+1;const result=await db.batch([db.prepare('UPDATE companies SET state=?,version=?,op=? WHERE id=? AND version=? AND EXISTS (SELECT 1 FROM members WHERE company=? AND user=?)').bind(JSON.stringify(state),revision,op,id,body.version,id,user.userId),db.prepare('INSERT INTO history (id,company,version,actor,reason,created,snapshot) SELECT ?,id,version,?,?,?,? FROM companies WHERE id=? AND op=?').bind(op,user.email,body.reason.trim(),now,JSON.stringify({...state,calculationVersion:ENGINE,results:state.entries.map(e=>({entryId:e.id,...calculate(e,state.convention)}))}),id,op)]);if(!result[0].meta.changes)return json({error:'Outra pessoa salvou alterações. Recarregue antes de editar novamente.'},409);return json({version:revision});}catch(error:any){if(error?.name==='ZodError'||error instanceof SyntaxError)return json({error:'Verifique os campos: valores, datas, nomes e competências duplicadas.'},400);return json({error:'Não foi possível salvar. Seus dados em edição foram preservados.'},503);}}

