import type { Employee, Monthly } from './management';
export const ENGINE='sol-2026.4';
export type Entry={employeeId?:string;monthly?:Monthly;id:string;employee:string;admission:string;month:string;salary:number;danger:boolean;annuityRate:number;bonus:number;extra50:number;extra100:number;workDays:number;restDays:number;absenceDiscount:number;otherDiscount:number;inssBase:number|null;irrf:number|null;paid:number|null;confirmed:boolean;original?:{file:string;cells:Record<string,unknown>;warnings:string[]};};
export type State={holidays?:import('./holidays').Holiday[];company:string;city:string;uf:string;convention:string;entries:Entry[];employees?:Employee[]};
export const initialState=():State=>({company:'SOL Provedor',city:'São João de Pirabas',uf:'PA',convention:'',entries:[]});
export const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n);
export const round=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;
export function yearsAt(admission:string,month:string){const [y,m]=month.split('-').map(Number),[ay,am,ad]=admission.split('-').map(Number);const end=new Date(Date.UTC(y,m,0)).getUTCDate();return Math.max(0,y-ay-((m<am||(m===am&&end<ad))?1:0));}
export function inss2026(base:number){let last=0;let sum=0;const bands=[];for(const [limit,rate] of [[162100,750],[290284,900],[435427,1200],[847555,1400]]){const taxable=Math.max(0,Math.min(Math.round(base*100),limit)-last);const cents=Math.floor(taxable*rate/10000);if(taxable)bands.push({base:taxable/100,rate:rate/100,value:cents/100});sum+=cents;last=limit;}return {total:sum/100,bands};}
export function calculate(e:Entry,convention='') {const years=yearsAt(e.admission,e.month);const danger=round(e.salary*(e.danger?.3:0));const annuity=round(e.salary*years*e.annuityRate/100);const hourly=e.monthly?e.monthly.hourlyBase/e.monthly.divisor:0;const extra50=e.monthly?round(hourly*e.monthly.hours50*1.5):e.extra50;const extra100=e.monthly?round(hourly*e.monthly.hours100*2):e.extra100;const unhealthy=e.monthly?round(e.monthly.unhealthyBase*e.monthly.unhealthyRate/100):0;const nightReducedHours=e.monthly?(e.monthly.nightClockHours?e.monthly.nightHours*60/52.5:e.monthly.nightHours):0;const night=e.monthly&&e.monthly.nightEligible!==false?round(hourly*nightReducedHours*(e.monthly.nightClockHours?20:e.monthly.nightRate)/100):0;const fixed=e.monthly?.fixedValue??0;const commission=e.monthly?.commission??0;const advance=e.monthly?.advance??0;const extras=round(extra50+extra100);const dsr=extras&&e.workDays>0?round(extras/e.workDays*e.restDays):0;const additionalTotal=round(danger+annuity+e.bonus+extras+dsr+unhealthy+night+fixed+commission);const gross=round(e.salary+additionalTotal);const base=e.inssBase??Math.max(0,round(gross-e.absenceDiscount));const contribution=e.month.startsWith('2026-')?inss2026(base):null;const warnings:string[]=[];if(e.monthly?.nightClockHours)warnings.push('Anuênio automático: premissa de 1% por ano completo, pendente de validação da convenção.');if(e.monthly?.nightEligible)warnings.push('Noturno urbano: confira convenção, prorrogações, jornada especial e reflexos no DSR; não incluídos automaticamente.');if(e.monthly&&!e.monthly.calendarConfirmed)warnings.push('Confirme os dias úteis, repousos e feriados locais.');if(e.monthly&&e.admission.slice(0,7)===e.month)warnings.push('Mês de admissão: confira a proporcionalidade do salário e adicionais.');if(e.danger&&unhealthy>0)warnings.push('Periculosidade e insalubridade simultâneas: revisar o enquadramento.');if(!convention.trim())warnings.push('Identifique a convenção coletiva e a regra aplicável.');if(!contribution)warnings.push('Tabela de INSS não cadastrada para este ano.');if(e.inssBase===null)warnings.push('Confirme a base de INSS e as incidências das rubricas.');if(e.irrf===null)warnings.push('Informe o IRRF apurado, inclusive quando for zero.');if(extras&&e.workDays<=0)warnings.push('Informe os dias úteis para o DSR.');if(!e.confirmed)warnings.push('Confira jornada, calendário, adicionais e descontos.');if(e.admission.slice(0,7)>e.month)warnings.push('Competência anterior à admissão.');const net=contribution?round(gross-contribution.total-(e.irrf??0)-e.absenceDiscount-e.otherDiscount-advance):null;return {engine:ENGINE,additionalTotal,nightReducedHours,hourly,extra50,extra100,unhealthy,night,fixed,commission,advance,years,danger,annuity,dsr,gross,base,contribution,net,warnings,difference:net!==null&&e.paid!==null?round(net-e.paid):null};}
export function blankEntry():Entry{return {id:crypto.randomUUID(),employee:'',admission:'2024-01-01',month:'2026-01',salary:0,danger:false,annuityRate:0,bonus:0,extra50:0,extra100:0,workDays:26,restDays:5,absenceDiscount:0,otherDiscount:0,inssBase:null,irrf:null,paid:null,confirmed:false};}
export function annual(base:number,average:number,units:number,type:'13'|'vacation'){const principal=round((base+average)*units/(type==='13'?12:30));return {principal,third:type==='vacation'?round(principal/3):0,total:type==='vacation'?round(principal+round(principal/3)):principal};}
