import { blankEntry,type Entry } from './engine';
// Strict, bounded XLSX reader for the supplied SOL template. No formula evaluation.
export async function importSol(file:File):Promise<{entries:Entry[];skipped:number;warnings:string[]}>{
if(!file.name.toLowerCase().endsWith('.xlsx')||file.size>5000000)throw new Error('Use um arquivo .xlsx de até 5 MB no modelo SOL.');
const bytes=new Uint8Array(await file.arrayBuffer()),v=new DataView(bytes.buffer),decoder=new TextDecoder();let end=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(v.getUint32(i,true)===0x06054b50){end=i;break;}if(end<0)throw new Error('Arquivo XLSX inválido.');let p=v.getUint32(end+16,true),count=v.getUint16(end+10,true),total=0;const files=new Map<string,Uint8Array>();if(count>200)throw new Error('O arquivo possui itens demais. Use o modelo SOL.');for(let i=0;i<count;i++){if(p+46>bytes.length||v.getUint32(p,true)!==0x02014b50)throw new Error('Arquivo corrompido.');const method=v.getUint16(p+10,true),size=v.getUint32(p+20,true),uncompressed=v.getUint32(p+24,true),n=v.getUint16(p+28,true),extra=v.getUint16(p+30,true),comment=v.getUint16(p+32,true),offset=v.getUint32(p+42,true),name=decoder.decode(bytes.slice(p+46,p+46+n));p+=46+n+extra+comment;if(!name.endsWith('.xml')&&!name.endsWith('.rels'))continue;total+=uncompressed;if(uncompressed>5000000||total>15000000)throw new Error('Conteúdo descompactado excede o limite.');if(offset+30>bytes.length)throw new Error('Arquivo corrompido.');const start=offset+30+v.getUint16(offset+26,true)+v.getUint16(offset+28,true);if(start+size>bytes.length)throw new Error('Arquivo corrompido.');let data=bytes.slice(start,start+size);if(method===8){const reader=new Blob([data]).stream().pipeThrough(new DecompressionStream('deflate-raw')).getReader();const chunks:Uint8Array[]=[];let length=0;for(;;){const {done,value}=await reader.read();if(done)break;length+=value.length;if(length>5000000){await reader.cancel();throw new Error('Conteúdo descompactado excede o limite.');}chunks.push(value);}data=new Uint8Array(length);let at=0;for(const c of chunks){data.set(c,at);at+=c.length;}}else if(method!==0)throw new Error('Compactação não suportada.');files.set(name,data);}
const xml=(name:string)=>{const b=files.get(name);if(!b)throw new Error('Modelo XLSX incompleto.');const doc=new DOMParser().parseFromString(decoder.decode(b),'application/xml');if(doc.querySelector('parsererror'))throw new Error('XML inválido.');return doc;};
const strings=files.has('xl/sharedStrings.xml')?Array.from(xml('xl/sharedStrings.xml').getElementsByTagName('si')).map(x=>x.textContent??''):[];
const workbook=xml('xl/workbook.xml');if(workbook.querySelector('workbookPr')?.getAttribute('date1904')==='1')throw new Error('Datas no sistema 1904 não são suportadas.');const rels=xml('xl/_rels/workbook.xml.rels'),sheet=Array.from(workbook.getElementsByTagName('sheet')).find(x=>x.getAttribute('name')==='Planilha1');if(!sheet)throw new Error('Esperada a aba Planilha1 do modelo SOL.');const rel=Array.from(rels.getElementsByTagName('Relationship')).find(x=>x.getAttribute('Id')===sheet.getAttribute('r:id'));const target=rel?.getAttribute('Target');if(!target)throw new Error('Aba não encontrada.');const path=target.startsWith('/')?target.slice(1):'xl/'+target;const cells=new Map<string,{value:string|number|null;formula:string|null}>();for(const c of Array.from(xml(path).getElementsByTagName('c'))){const t=c.getAttribute('t'),raw=c.querySelector('v')?.textContent;let value:string|number|null=raw??null;if(t==='s')value=strings[Number(raw)]??'';else if(t==='inlineStr')value=c.querySelector('is')?.textContent??'';else if(raw!==undefined&&raw!==null&&t!=='str'&&t!=='e')value=Number(raw);cells.set(c.getAttribute('r')!,{value,formula:c.querySelector('f')?.textContent??null});}
const val=(key:string)=>cells.get(key)?.value;
if(val('B5')!=='MENSALISTA'||val('B20')!=='BRUTO'||typeof val('A4')!=='string')throw new Error('A estrutura deve seguir o modelo SOL: nome em A4 e rubricas em B5:B23.');
const year=Number(val('Q1'));if(!Number.isInteger(year)||year<2000||year>2099)throw new Error('Ano inválido em Q1.');const admission=val('P7');if(typeof admission!=='number')throw new Error('Admissão inválida em P7.');const date=new Date(Date.UTC(1899,11,30)+admission*86400000).toISOString().slice(0,10);
const warnings=['O valor pago não é inferido do líquido da planilha. Informe-o a partir do comprovante.','Férias: a fórmula original usa mediana do líquido e 30%; refaça com a remuneração aplicável e um terço.','13º: a fórmula original usa líquido/12; refaça a partir da remuneração e dos avos devidos.','Anuênio: a fórmula original usa TODAY(); o sistema usa a competência.','Soma de variáveis original inclui o INSS como parcela positiva; revise as médias.'];
const entries:Entry[]=[];let skipped=0;for(let m=1;m<=12;m++){const col=String.fromCharCode(66+m);const num=(r:number)=>{const value=val(col+r);if(value==null)return 0;if(typeof value!=='number'||!Number.isFinite(value)||value<0)throw new Error('Valor inválido em '+col+r);return value;};if(num(5)===0){skipped++;continue;}const e=blankEntry();Object.assign(e,{employee:String(val('A4')),admission:date,month:`${year}-${String(m).padStart(2,'0')}`,salary:num(5),danger:val('P6')==='Sim',annuityRate:1,bonus:num(8),extra100:num(9),extra50:num(10),workDays:Math.max(0,Math.min(31,num(13))),restDays:Math.max(0,Math.min(31,num(15))),absenceDiscount:num(18),otherDiscount:num(19)});const raw:Record<string,string|number|null>={};for(let r=4;r<=23;r++){const c=cells.get(col+r);if(c){raw[col+r]=c.value;if(c.formula)raw[col+r+' formula']=c.formula;}}e.original={file:file.name,cells:raw,warnings:[...warnings,...(m>1?['A fórmula do líquido deste mês não desconta faltas nem outros descontos.']:[])]};entries.push(e);}if(!entries.length)throw new Error('Nenhum mês com salário informado.');return {entries,skipped,warnings};}
