'use client';
import {useState} from 'react';
import type {State} from '@/lib/payroll/engine';
import {money,annual} from '@/lib/payroll/engine';
import {currentMonth} from '@/lib/payroll/management';
import {employeeAnnual,vacationPeriod} from '@/lib/payroll/annual-employee';
export default function AnnualCalculator({state}:{state:State}){
 const [id,setId]=useState(''),[type,setType]=useState<'13'|'vacation'>('13'),[reference,setReference]=useState(`${currentMonth().slice(0,4)}-12-31`),[start,setStart]=useState(''),[absences,setAbsences]=useState<number|null>(null),[installment,setInstallment]=useState<'annual'|'first'|'second'>('annual'),[override,setOverride]=useState<number|null>(null);
 const p=state.employees?.find(e=>e.id===id);let data:ReturnType<typeof employeeAnnual>|null=null,error='';if(p)try{data=employeeAnnual(state,p,type,reference,start||vacationPeriod(p,reference),absences,installment,reference);}catch(e:any){error=e.message;}
 const result=data&&data.units!==null?annual(data.fixed,override??data.average,data.units,type):null;
 const reset=()=>{setOverride(null);setAbsences(null);setStart('');setInstallment('annual');};
 return <section className="panel"><div className="panel-heading"><div><h2>Férias e 13º por colaborador</h2><p>Salário vigente, adicionais e médias dos lançamentos preenchidos automaticamente.</p></div><span className="badge">PRÉVIA BRUTA</span></div><div className="form-grid"><label className="field"><span>Colaborador</span><select value={id} onChange={e=>{setId(e.target.value);reset();}}><option value="">Selecione o colaborador</option>{state.employees?.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="field"><span>Tipo</span><select value={type} onChange={e=>{setType(e.target.value as '13'|'vacation');reset();}}><option value="13">13º salário</option><option value="vacation">Férias integrais adquiridas</option></select></label><label className="field"><span>{type==='13'?'Data de pagamento':'Data de concessão das férias'}</span><input type="date" required value={reference} onChange={e=>{setReference(e.target.value);reset();}}/></label>{type==='13'&&<label className="field"><span>Parcela do 13º</span><select value={installment} onChange={e=>{setInstallment(e.target.value as any);setOverride(null);}}><option value="annual">Total anual</option><option value="first">1ª parcela · adiantamento</option><option value="second">2ª parcela · saldo</option></select></label>}{type==='vacation'&&<><label className="field"><span>Início do período aquisitivo</span><input type="date" value={start||(p&&reference?vacationPeriod(p,reference):'')} onChange={e=>{setStart(e.target.value);setOverride(null);setAbsences(null);}}/></label><label className="field"><span>Faltas injustificadas no período (dias)</span><input type="number" min="0" max="366" step="1" value={absences??''} placeholder="Informe zero se não houver" onChange={e=>setAbsences(e.target.value===''?null:Math.max(0,Math.floor(Number(e.target.value))))}/></label></>}</div>
 {error&&<p className="notice error">{error}</p>}{data&&<><div className="contract-strip"><span>Remuneração fixa: <strong>{money(data.fixed)}</strong></span><span>Média automática {data.missing.length?'parcial':''}: <strong>{money(data.average)}</strong></span><span>{type==='13'?`${data.avos}/12 avos até o pagamento`:`${data.days??'—'} dias de direito`}</span></div><p className="note">Período: {data.begin} a {data.end}. {data.records.length} competências localizadas. Horas extras médias valorizadas pela hora atual; comissões nas férias usam os meses disponíveis nos 12 meses anteriores. Médias dependem da conferência das regras aplicáveis.</p><details><summary>Ajustar média após conferência do contador</summary><label className="field"><span>Média validada (R$) — em branco usa a automática</span><input type="number" min="0" step="0.01" value={override??''} onChange={e=>setOverride(e.target.value===''?null:Math.max(0,Number(e.target.value)))}/></label></details>
 {result?<div className="calculation-result"><div><small>Principal anual</small><strong>{money(result.principal)}</strong></div>{type==='vacation'&&<div><small>Terço constitucional</small><strong>{money(result.third)}</strong></div>}{type==='13'&&installment!=='annual'&&<div><small>{installment==='first'?'Valor da 1ª parcela':'Valor da 2ª parcela'}</small><strong>{money(data.installmentValue??0)}</strong></div>}<div><small>{type==='13'&&installment!=='annual'?'Total bruto devido':'Total bruto preliminar'}</small><strong>{money(result.total)}</strong></div></div>:<p className="notice">Informe as faltas em dias para calcular os dias de férias e o valor.</p>}
 <ul className="warning-list">{data.warnings.map(w=><li key={w}>{w}</li>)}</ul></>}
 {!p&&<p className="note">Selecione um colaborador para apurar os valores.</p>}<p className="sources"><a href="https://www.planalto.gov.br/ccivil_03/leis/l4090.htm" target="_blank" rel="noreferrer">13º — Lei 4.090/1962</a> · <a href="https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452compilado.htm" target="_blank" rel="noreferrer">Férias — CLT, arts. 130 e 142</a></p></section>;
}
