'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import type {State} from '@/lib/payroll/engine';
import {currentMonth} from '@/lib/payroll/management';
import {holidaysFor,type Holiday} from '@/lib/payroll/holidays';
export default function HolidayCalendar({state,onSave}:{state:State;onSave:(s:State,reason:string)=>Promise<void>}){
 const [year,setYear]=useState(currentMonth().slice(0,4)),[date,setDate]=useState(''),[name,setName]=useState(''),[source,setSource]=useState(''),[scope,setScope]=useState<Holiday['scope']>('municipal'),[busy,setBusy]=useState(false);
 const list=holidaysFor(state,year);
 async function save(h:Holiday){setBusy(true);try{await onSave({...state,holidays:[...(state.holidays??[]).filter(v=>v.id!==h.id),h]},'Atualização do calendário de feriados');toast.success('Calendário salvo. Meses já lançados precisam ser atualizados individualmente.');return true;}catch(e:any){toast.error(e.message);return false;}finally{setBusy(false);}}
 return <section className="panel"><div className="panel-heading"><div><h2>Feriados do ano</h2><p>{state.city}/{state.uf} · calendário aplicado aos novos lançamentos.</p></div><label className="field"><span>Ano</span><input type="number" min="2000" max="2099" value={year} onChange={e=>{if(/^20\d{2}$/.test(e.target.value))setYear(e.target.value);}}/></label></div>
 <p className="note">Feriados nacionais fixos e 15 de agosto no Pará já estão disponíveis. Outros estados e feriados municipais podem ser cadastrados abaixo. Carnaval, Corpus Christi e pontos facultativos não entram automaticamente. Cadastre a Sexta-feira da Paixão conforme a lei municipal aplicável. Datas futuras devem ser conferidas a cada ano.</p>
 <div className="indicator-scroll"><table><thead><tr><th>Usar no DSR</th><th>Data</th><th>Feriado</th><th>Abrangência</th><th>Fundamento</th></tr></thead><tbody>{list.map(h=><tr key={h.id}><td><input type="checkbox" aria-label={`Usar ${h.name} no DSR`} checked={h.enabled} disabled={busy} onChange={e=>save({...h,enabled:e.target.checked})}/></td><td>{h.date.split('-').reverse().join('/')}</td><td>{h.name}</td><td>{{national:'Nacional',state:'Estadual',municipal:'Municipal'}[h.scope]}</td><td>{h.source}</td></tr>)}</tbody></table></div>
 <h3 style={{marginTop:24}}>Cadastrar feriado</h3><form onSubmit={async e=>{e.preventDefault();if(!date.startsWith(year+'-')){toast.error('Escolha uma data dentro do ano selecionado.');return;}if(await save({id:crypto.randomUUID(),date,name:name.trim(),source:source.trim(),scope,uf:scope==='national'?'':state.uf,city:scope==='municipal'?state.city:'',enabled:true})){setDate('');setName('');setSource('');}}}><div className="form-grid"><label className="field"><span>Data</span><input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field"><span>Nome do feriado</span><input required maxLength={150} value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>Abrangência</span><select value={scope} onChange={e=>setScope(e.target.value as Holiday['scope'])}><option value="municipal">Municipal · {state.city}</option><option value="state">Estadual · {state.uf}</option><option value="national">Nacional</option></select></label><label className="field"><span>Lei ou fundamento</span><input required maxLength={500} value={source} onChange={e=>setSource(e.target.value)}/></label></div><button disabled={busy} className="primary">Cadastrar feriado</button></form>
 <p className="note">Domingos e feriados coincidentes contam uma única vez. Sábado continua considerado útil; confira a jornada do colaborador.</p><p className="sources"><a href="https://www.agenciapara.com.br/noticia/73545/governo-do-para-divulga-datas-de-feriados-e-pontos-facultativos-para-2026" target="_blank" rel="noreferrer">Calendário oficial do Pará</a> · <a href="https://www.planalto.gov.br/ccivil_03/leis/l9093.htm" target="_blank" rel="noreferrer">Lei 9.093/1995</a></p>
 </section>;
}
