'use client';
import {useState} from 'react';
import {money,round,type State,type Entry,calculate} from '@/lib/payroll/engine';
import {currentMonth} from '@/lib/payroll/management';
import {indicators,personKey} from '@/lib/payroll/indicators';
const names=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];
type Result=ReturnType<typeof calculate>;
const rubrics:{label:string;value:(e:Entry,c:Result)=>number|null;unit?:string;highlight?:boolean}[]=[
 {label:'Salário',value:e=>e.salary},{label:'Periculosidade',value:(_,c)=>c.danger},{label:'Insalubridade',value:(_,c)=>c.unhealthy},{label:'Anuênio',value:(_,c)=>c.annuity},{label:'Outros adicionais fixos',value:(_,c)=>c.fixed},{label:'Adicional noturno',value:(_,c)=>c.night},
 {label:'Horas extras 50%',value:(_,c)=>c.extra50},{label:'Horas extras 100%',value:(_,c)=>c.extra100},{label:'DSR sobre horas extras',value:(_,c)=>c.dsr},{label:'Bonificação',value:e=>e.bonus},{label:'Comissões',value:(_,c)=>c.commission},{label:'Total de adicionais e verbas variáveis',value:(_,c)=>c.additionalTotal,highlight:true},{label:'Bruto',value:(_,c)=>c.gross,highlight:true},
 {label:'Base INSS',value:(_,c)=>c.base},{label:'INSS',value:(_,c)=>c.contribution?.total??null},{label:'IRRF informado',value:e=>e.irrf},{label:'Faltas / perda de DSR',value:e=>e.absenceDiscount},{label:'Adiantamento',value:(_,c)=>c.advance},{label:'Outros descontos',value:e=>e.otherDiscount},{label:'Líquido preliminar',value:(_,c)=>c.net,highlight:true},{label:'Valor pago',value:e=>e.paid},{label:'Diferença a conferir',value:(_,c)=>c.difference},
 {label:'Quantidade H.E. 50%',value:e=>e.monthly?.hours50??null,unit:'h'},{label:'Quantidade H.E. 100%',value:e=>e.monthly?.hours100??null,unit:'h'},{label:'Horas noturnas reduzidas',value:(e,c)=>e.monthly?c.nightReducedHours:null,unit:'h'},{label:'Dias úteis para DSR',value:e=>e.workDays,unit:'dias'},{label:'Repousos / feriados',value:e=>e.restDays,unit:'dias'}
];
export default function PayrollIndicators({state}:{state:State}){
 const now=currentMonth();const [year,setYear]=useState(now.slice(0,4)),[month,setMonth]=useState(Number(now.slice(5))-1),[person,setPerson]=useState('');
 const years=[...new Set([now.slice(0,4),...state.entries.map(e=>e.month.slice(0,4))])].sort().reverse();const data=indicators(state,year);
 const options=new Map((state.employees??[]).map(p=>[p.id,p.name]));for(const {entry:e} of data.entries)if(!options.has(personKey(e)))options.set(personKey(e),e.employee);
 const selected=options.has(person)?person:[...options.keys()][0]??'';const individual=data.entries.filter(r=>personKey(r.entry)===selected);const columns=names.map((_,i)=>individual.find(r=>Number(r.entry.month.slice(5))===i+1));
 const format=(n:number,unit?:string)=>unit?`${n.toLocaleString('pt-BR',{maximumFractionDigits:2})} ${unit}`:money(n);
 return <div className="indicators"><section className="panel"><div className="panel-heading"><div><h2>Indicadores de colaboradores</h2><p>Acompanhe a remuneração e as horas extras dos lançamentos salvos.</p></div><div className="inline-actions"><label className="field"><span>Ano</span><select value={year} onChange={e=>setYear(e.target.value)}>{years.map(y=><option key={y}>{y}</option>)}</select></label><label className="field"><span>Mês de referência</span><select value={month} onChange={e=>setMonth(Number(e.target.value))}>{names.map((n,i)=><option value={i} key={n}>{n}</option>)}</select></label></div></div>
 <div className="cards"><article><span>Gasto mensal · {names[month]}/{year}</span><strong className="money">{data.months[month].count?money(data.months[month].gross):'Sem lançamento'}</strong><small>{data.months[month].count} lançamento(s)</small></article><article><span>Gasto anual · {year}</span><strong className="money">{data.entries.length?money(data.gross):'Sem lançamento'}</strong><small>{data.months.filter(m=>m.count).length} de 12 meses com dados</small></article><article className="accent"><span>Horas extras no ano</span><strong className="money">{data.entries.length?money(data.extras):'Sem lançamento'}</strong><small>DSR sobre H.E. separado: {money(data.dsr)}</small></article></div>
 <p className="note">Gasto = remuneração bruta registrada, antes dos descontos. Não inclui encargos patronais, FGTS, benefícios ou provisões de férias e 13º. O anual soma apenas meses salvos, sem projeção. {data.pending} lançamento(s) com pendências de conferência.</p>
 </section><section className="panel"><h2>Gasto mensal de colaboradores · {year}</h2><div className="annual-bars">{data.months.map((m,i)=><button key={m.month} className={month===i?'selected':''} onClick={()=>setMonth(i)} aria-label={`${names[i]}: ${m.count?money(m.gross):'sem lançamento'}`}><span>{names[i]}</span><span className="bar-track"><span style={{width:`${m.gross/Math.max(1,...data.months.map(v=>v.gross))*100}%`}}/></span><strong>{m.count?money(m.gross):'—'}</strong></button>)}</div></section>
 <section className="panel"><h2>Top horas extras · {year}</h2><p>Ranking por valor anual de H.E. 50% + 100%, sem DSR.</p><div className="indicator-scroll"><table><thead><tr><th>Posição</th><th>Colaborador</th><th>Quantidade</th><th>Valor anual</th></tr></thead><tbody>{data.ranking.slice(0,10).map((r,i)=><tr key={r.id}><td>{i+1}º</td><td><button className="text-button" onClick={()=>setPerson(r.id)}>{r.name}</button></td><td>{r.hours.toLocaleString('pt-BR')} h{r.missingHours?' (parcial)':''}</td><td>{money(r.value)}</td></tr>)}</tbody></table></div>{!data.ranking.length&&<p className="note">Não há horas extras registradas neste ano.</p>}</section>
 <section className="panel"><div className="panel-heading"><div><h2>Comparativo anual por colaborador</h2><p>Meses lado a lado e total anual de cada informação.</p></div><label className="field"><span>Colaborador</span><select value={selected} onChange={e=>setPerson(e.target.value)}><option value="" disabled>Selecione</option>{[...options].sort((a,b)=>a[1].localeCompare(b[1])).map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label></div>
 {!individual.length?<p className="note">Nenhum lançamento para este colaborador em {year}.</p>:<><p className="note">{individual.length} de 12 meses registrados. “—” indica mês sem lançamento; “Não informado” indica um campo pendente. Totais parciais somam somente valores disponíveis.</p><div className="indicator-scroll" tabIndex={0} role="region" aria-label="Comparativo mensal com rolagem horizontal"><table className="annual-comparison"><thead><tr><th>Informação</th>{names.map(n=><th key={n}>{n}/{year}</th>)}<th>Total anual</th></tr></thead><tbody><tr><th>Situação</th>{columns.map((r,i)=><td key={i}>{r?(r.result.warnings.length?'Pendente':'Conferido'):'—'}</td>)}<td>{individual.length} meses</td></tr>{rubrics.map(row=>{const values=columns.map(r=>r?row.value(r.entry,r.result):null);const known=values.filter((v):v is number=>v!==null);const partial=individual.length<12||known.length<individual.length;return <tr key={row.label} className={row.highlight?'annual-highlight':''}><th>{row.label}</th>{columns.map((r,i)=><td key={i}>{!r?'—':values[i]===null?'Não informado':format(values[i]!,row.unit)}</td>)}<td><strong>{known.length?format(round(known.reduce((s,v)=>s+v,0)),row.unit):'Não informado'}</strong>{partial&&known.length>0&&<small>Parcial</small>}</td></tr>})}</tbody></table></div></>}
 </section></div>;
}
