'use client';
import {useEffect,useState} from 'react';
import {holidayDates} from '@/lib/payroll/holidays';
import EmployeeImport from './employee-import';
import {mergeImported} from '@/lib/payroll/import-employees';
import {Users,CalendarDays,Calculator,Plus,ArrowRight,FileDown} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {toast} from 'sonner';
import {calculate,money,yearsAt,type Entry,type State} from '@/lib/payroll/engine';
import {blankEmployee,blankContract,currentMonth,contractAt,entryFor,calendar,type Employee,type Contract} from '@/lib/payroll/management';
import {employeeSchema} from '@/lib/payroll/management-validation';

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function NumberField({label,value,onChange,optional=false,max=100000000,step='0.01'}:{label:string;value:number|null;onChange:(value:number|null)=>void;optional?:boolean;max?:number;step?:string}){return <Field label={label}><input type="number" min="0" max={max} step={step} required={!optional} value={value??''} onChange={e=>onChange(e.target.value===''&&optional?null:Number(e.target.value))}/></Field>}
export default function PayrollFlow({state,onSave,view,setView}:{state:State;onSave:(next:State,reason:string)=>Promise<void>;view:string;setView:(value:string)=>void}){
  const [month,setMonth]=useState(currentMonth),[personId,setPersonId]=useState(''),[query,setQuery]=useState('');
  const [employee,setEmployee]=useState<Employee|null>(null),[contract,setContract]=useState<Contract>(blankContract),[draft,setDraft]=useState<Entry|null>(null),[detail,setDetail]=useState<Entry|null>(null),[reason,setReason]=useState(''),[saving,setSaving]=useState(false);
  const employees=state.employees??[],entries=state.entries.filter(e=>e.month===month);
  const [peoplePage,setPeoplePage]=useState(1);
  const [entriesPage,setEntriesPage]=useState(1);
  const entriesPageCount=Math.max(1,Math.ceil(entries.length/10));
  const activeEntriesPage=Math.min(entriesPage,entriesPageCount);
  const pageEntries=entries.slice((activeEntriesPage-1)*10,activeEntriesPage*10);
  useEffect(()=>setEntriesPage(1),[month]);
  useEffect(()=>setEntriesPage(p=>Math.min(p,entriesPageCount)),[entriesPageCount]);
  const people=employees.filter(e=>`${e.name} ${e.registration} ${e.job}`.toLowerCase().includes(query.toLowerCase()));
  const pageCount=Math.max(1,Math.ceil(people.length/10));
  const activePage=Math.min(peoplePage,pageCount);
  const pagePeople=people.slice((activePage-1)*10,activePage*10);
  useEffect(()=>setPeoplePage(p=>Math.min(p,pageCount)),[pageCount]);
  const eligible=employees.filter(e=>e.admission.slice(0,7)<=month&&(!e.termination||e.termination.slice(0,7)>=month));
  const results=entries.map(e=>({entry:e,result:calculate(e,state.convention)}));
  const [resultsPage,setResultsPage]=useState(1);
  const resultsPageCount=Math.max(1,Math.ceil(results.length/10));
  const activeResultsPage=Math.min(resultsPage,resultsPageCount);
  const pageResults=results.slice((activeResultsPage-1)*10,activeResultsPage*10);
  useEffect(()=>setResultsPage(1),[month]);
  useEffect(()=>setResultsPage(p=>Math.min(p,resultsPageCount)),[resultsPageCount]);
  async function persist(next:State,why:string,done:()=>void){setSaving(true);try{await onSave(next,why);done();}catch(e:any){toast.error(e.message);}finally{setSaving(false);}}
  function openEmployee(e:Employee){setEmployee(structuredClone(e));setContract(structuredClone([...e.contracts].sort((a,b)=>b.effective.localeCompare(a.effective))[0]));setReason('');}
  async function removeEmployee(p:Employee){const linked=state.entries.some(e=>e.employeeId===p.id);if(linked){toast.error('Não é possível excluir: este colaborador possui lançamentos salvos. Preserve o histórico e use a data de desligamento.');return;}if(!window.confirm(`Excluir o cadastro de ${p.name||'colaborador'}? Esta ação não pode ser desfeita.`))return;await persist({...state,employees:employees.filter(e=>e.id!==p.id)},'Exclusão do cadastro de colaborador',()=>toast.success('Colaborador excluído.'));}
  function newMonth(p:Employee,m:string){const e=entryFor(p,m);const holidays=holidayDates(state,m);return {...e,...calendar(m,holidays),monthly:{...e.monthly!,holidays}};}
  function openMonth(id=personId){const p=employees.find(e=>e.id===id);if(!p){toast.error('Selecione um colaborador cadastrado.');return;}try{const existing=state.entries.find(e=>e.employeeId===p.id&&e.month===month);setDraft(existing?structuredClone(existing):newMonth(p,month));setPersonId(id);setReason(existing?'':'Inclusão de ocorrências mensais');setView('monthly');}catch(e:any){toast.error(e.message);}}
  function setEntry(key:keyof Entry,value:unknown){if(draft)setDraft({...draft,[key]:value,confirmed:key==='confirmed'?value===true:false});}
  function setMonthly(key:string,value:unknown){if(draft?.monthly)setDraft({...draft,monthly:{...draft.monthly,[key]:value},confirmed:false});}
  function exportResults(){const rows=[['Colaborador','Matrícula','Competência','Bruto','Horas extras','DSR','INSS','IRRF informado','Líquido preliminar','Pago','Diferença','Pendências'],...results.map(({entry:e,result:c})=>[e.employee,employees.find(p=>p.id===e.employeeId)?.registration??'',e.month,c.gross,c.extra50+c.extra100,c.dsr,c.contribution?.total??'',e.irrf??'',c.net??'',e.paid??'',c.difference??'',c.warnings.join(' / ')])];const quote=(v:unknown)=>'"'+String(v).replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(quote).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`folha-${month}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const calculated=draft?calculate(draft,state.convention):null;
  const monthlyField=(key:string,label:string,max?:number)=>draft?.monthly&&<NumberField label={label} value={(draft.monthly as any)[key]} max={max} onChange={v=>setMonthly(key,v)}/>;
  const entryField=(key:keyof Entry,label:string,optional=false)=>draft&&<NumberField label={label} value={draft[key] as number|null} optional={optional} onChange={v=>setEntry(key,v)}/>;
  return <section className="payroll-flow">
    <Tabs value={view} onValueChange={setView}>
      <TabsContent value="employees"><section className="panel">
        <div className="panel-heading"><div><h2>Cadastro de colaboradores</h2><p>Dados do vínculo, salário e adicionais recorrentes. Cadastro único por matrícula.</p></div><div className="inline-actions"><EmployeeImport employees={employees} onImport={async added=>{await onSave({...state,employees:mergeImported(employees,added)},`Importação de ${added.length} colaboradores via planilha`);}}/><button className="primary" onClick={()=>openEmployee(blankEmployee())}><Plus size={17}/> Cadastrar colaborador</button></div></div>
        <Field label="Buscar por nome, matrícula ou cargo"><input value={query} onChange={e=>{setQuery(e.target.value);setPeoplePage(1);}} placeholder="Buscar colaborador"/></Field>
        <Table className="compact-employees-table"><TableHeader><TableRow><TableHead>Colaborador</TableHead><TableHead>Cargo / setor</TableHead><TableHead>Salário atual</TableHead><TableHead>Vínculo</TableHead><TableHead>Ações</TableHead></TableRow></TableHeader><TableBody>{pagePeople.map(p=>{const c=contractAt(p,currentMonth());return <TableRow key={p.id}><TableCell><strong>{p.name}</strong><small className="block">Matrícula {p.registration||'pendente'}</small></TableCell><TableCell>{p.job}<small className="block">{p.department||'Setor não informado'}</small></TableCell><TableCell>{c?.salary?money(c.salary):'Salário pendente'}</TableCell><TableCell>{p.termination&&p.termination<new Date().toLocaleDateString('sv-SE')?'Encerrado':'Ativo'}</TableCell><TableCell><div className="employee-actions"><button className="secondary" onClick={()=>openEmployee(p)}>Editar ficha</button><button className="text-button" onClick={()=>{setPersonId(p.id);setView('monthly');}}>Lançar mês <ArrowRight size={15}/></button><button className="danger-button" onClick={()=>removeEmployee(p)}>Excluir</button></div></TableCell></TableRow>})}</TableBody></Table>
        {people.length>0&&<nav className="people-pagination" aria-label="Paginação de colaboradores"><span aria-live="polite">Mostrando {(activePage-1)*10+1}–{Math.min(activePage*10,people.length)} de {people.length} colaboradores</span><div className="inline-actions"><button type="button" className="secondary" disabled={activePage===1} onClick={()=>setPeoplePage(1)}>Primeira</button><button type="button" className="secondary" disabled={activePage===1} onClick={()=>setPeoplePage(activePage-1)}>Anterior</button><span>Página {activePage} de {pageCount}</span><button type="button" className="secondary" disabled={activePage===pageCount} onClick={()=>setPeoplePage(activePage+1)}>Próxima</button><button type="button" className="secondary" disabled={activePage===pageCount} onClick={()=>setPeoplePage(pageCount)}>Última</button></div></nav>}
        {!people.length&&<div className="empty"><Users size={30}/><h3>{employees.length?'Nenhum colaborador encontrado':'Cadastre o primeiro colaborador'}</h3><p>Informe os dados uma vez. Eles serão reaproveitados nas competências seguintes.</p></div>}
      </section></TabsContent>
      <TabsContent value="monthly"><section className="panel"><div className="panel-heading"><div><h2>Ocorrências da competência</h2><p>Selecione o mês e o colaborador. Salário e adicionais vêm do contrato vigente.</p></div></div>
        <div className="month-controls"><Field label="Competência dos lançamentos"><input type="month" required value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setDraft(null);}}}/></Field><Field label="Colaborador para lançamento"><Select value={personId} onValueChange={setPersonId}><SelectTrigger aria-label="Colaborador para lançamento"><SelectValue placeholder="Selecione o colaborador"/></SelectTrigger><SelectContent>{eligible.map(p=><SelectItem key={p.id} value={p.id}>{p.registration} · {p.name}</SelectItem>)}</SelectContent></Select></Field><button className="primary" disabled={!personId} onClick={()=>openMonth()}>Abrir lançamento</button></div>
        {!employees.length&&<div className="notice">Cadastre os colaboradores antes de lançar as ocorrências.<button onClick={()=>setView('employees')}>Ir para cadastro</button></div>}
        <div className="month-summary"><span>{eligible.length} colaboradores no vínculo</span><span>{entries.length} lançamentos salvos</span><span>{eligible.filter(p=>!entries.some(e=>e.employeeId===p.id)).length} ainda sem lançamento</span></div>
        {entries.length>0&&<Table className="compact-monthly-table"><TableHeader><TableRow><TableHead>Colaborador</TableHead><TableHead>Bonificação</TableHead><TableHead>Horas extras</TableHead><TableHead>Situação</TableHead><TableHead>Ação</TableHead></TableRow></TableHeader><TableBody>{pageEntries.map(e=><TableRow key={e.id}><TableCell>{e.employee}</TableCell><TableCell>{money(e.bonus)}</TableCell><TableCell>{e.monthly?`${e.monthly.hours50+e.monthly.hours100} h`:'Registro anterior'}</TableCell><TableCell>{calculate(e,state.convention).warnings.length?'Pendente de conferência':'Conferido'}</TableCell><TableCell><button className="secondary" onClick={()=>{setDraft(structuredClone(e));setReason('');}}>Editar mês</button></TableCell></TableRow>)}</TableBody></Table>}
        {entries.length>0&&<nav className="people-pagination" aria-label="Paginação dos lançamentos"><span aria-live="polite">Mostrando {(activeEntriesPage-1)*10+1}–{Math.min(activeEntriesPage*10,entries.length)} de {entries.length} lançamentos</span><div className="inline-actions"><button type="button" className="secondary" disabled={activeEntriesPage===1} onClick={()=>setEntriesPage(1)}>Primeira</button><button type="button" className="secondary" disabled={activeEntriesPage===1} onClick={()=>setEntriesPage(activeEntriesPage-1)}>Anterior</button><span>Página {activeEntriesPage} de {entriesPageCount}</span><button type="button" className="secondary" disabled={activeEntriesPage===entriesPageCount} onClick={()=>setEntriesPage(activeEntriesPage+1)}>Próxima</button><button type="button" className="secondary" disabled={activeEntriesPage===entriesPageCount} onClick={()=>setEntriesPage(entriesPageCount)}>Última</button></div></nav>}
        <button className="text-button" onClick={()=>setView('results')}>Ver resultados desta competência <ArrowRight size={16}/></button>
      </section></TabsContent>
      <TabsContent value="results"><section className="panel"><div className="panel-heading"><div><h2>Resultados calculados</h2><p>Valores gerados a partir do cadastro e dos lançamentos salvos.</p></div><div className="inline-actions"><Field label="Competência dos resultados"><input type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value)}}/></Field><button className="secondary" disabled={!results.length} onClick={exportResults}><FileDown size={16}/> Exportar resultados</button></div></div>
        <div className="cards"><article><span>Total bruto</span><strong className="money">{money(results.reduce((s,r)=>s+r.result.gross,0))}</strong></article><article><span>Líquido preliminar {results.some(r=>r.result.net===null)?'(parcial)':''}</span><strong className="money">{money(results.reduce((s,r)=>s+(r.result.net??0),0))}</strong></article><article className="accent"><span>Competências conferidas</span><strong>{results.filter(r=>!r.result.warnings.length).length} / {results.length}</strong></article></div>
        <Table className="compact-results-table"><TableHeader><TableRow><TableHead>Colaborador</TableHead><TableHead>Bruto</TableHead><TableHead>INSS</TableHead><TableHead>Líquido preliminar</TableHead><TableHead>Pendências</TableHead><TableHead>Memória</TableHead></TableRow></TableHeader><TableBody>{pageResults.map(({entry:e,result:c})=><TableRow key={e.id}><TableCell>{e.employee}</TableCell><TableCell>{money(c.gross)}</TableCell><TableCell>{c.contribution?money(c.contribution.total):'Não calculado'}</TableCell><TableCell>{c.net===null?'Não calculado':money(c.net)}</TableCell><TableCell><span className={'status '+(c.warnings.length?'pending':'ok')}>{c.warnings.length?`${c.warnings.length} pendências`:'Conferido'}</span></TableCell><TableCell><button className="secondary" onClick={()=>setDetail(e)}>Ver cálculo</button></TableCell></TableRow>)}</TableBody></Table>
        {results.length>0&&<nav className="people-pagination" aria-label="Paginação dos resultados"><span aria-live="polite">Mostrando {(activeResultsPage-1)*10+1}–{Math.min(activeResultsPage*10,results.length)} de {results.length} resultados</span><div className="inline-actions"><button type="button" className="secondary" disabled={activeResultsPage===1} onClick={()=>setResultsPage(1)}>Primeira</button><button type="button" className="secondary" disabled={activeResultsPage===1} onClick={()=>setResultsPage(activeResultsPage-1)}>Anterior</button><span>Página {activeResultsPage} de {resultsPageCount}</span><button type="button" className="secondary" disabled={activeResultsPage===resultsPageCount} onClick={()=>setResultsPage(activeResultsPage+1)}>Próxima</button><button type="button" className="secondary" disabled={activeResultsPage===resultsPageCount} onClick={()=>setResultsPage(resultsPageCount)}>Última</button></div></nav>}
        {!results.length&&<div className="empty"><Calculator size={30}/><h3>Sem lançamentos nesta competência</h3><p>Salve as ocorrências na segunda tela para ver os resultados aqui.</p><button className="secondary" onClick={()=>setView('monthly')}>Ir para lançamentos</button></div>}
      </section></TabsContent>
    </Tabs>
    <Dialog open={!!employee} onOpenChange={open=>{if(!open&&!saving)setEmployee(null)}}><DialogContent className="entry-dialog"><DialogTitle>Ficha do colaborador</DialogTitle><DialogDescription>Identificação e regras contratuais com vigência. Meses salvos preservam os dados usados no cálculo.</DialogDescription>
      {employee&&<form onSubmit={e=>{e.preventDefault();const automaticContract={...contract,annuityRate:1,nightRate:20,nightEligible:contract.nightEligible===true};const next={...employee,contracts:employees.some(p=>p.id===employee.id)?[...employee.contracts.filter(c=>c.effective!==contract.effective),automaticContract].sort((a,b)=>a.effective.localeCompare(b.effective)):[automaticContract]};const parsed=employeeSchema.safeParse(next);if(!parsed.success){toast.error(parsed.error.issues[0].message);return;}persist({...state,employees:employees.some(p=>p.id===next.id)?employees.map(p=>p.id===next.id?next:p):[...employees,next]},reason,()=>setEmployee(null));}}>
        <h3>Dados do vínculo</h3><div className="form-grid">
          {(['name','registration','job','department'] as const).map((key,i)=><Field key={key} label={['Nome completo','Matrícula','Cargo / função','Setor'][i]}><input required={key==='name'} value={employee[key]} onChange={e=>setEmployee({...employee,[key]:e.target.value})}/></Field>)}
          <Field label="PIS (opcional)"><input value={employee.pis??''} maxLength={11} inputMode="numeric" onChange={e=>setEmployee({...employee,pis:e.target.value.replace(/\D/g,'')})}/></Field><Field label="Admissão"><input type="date" value={employee.admission} onChange={e=>setEmployee({...employee,admission:e.target.value})}/></Field><Field label="Desligamento (opcional)"><input type="date" value={employee.termination} onChange={e=>setEmployee({...employee,termination:e.target.value})}/></Field>
        </div><h3>Salário, jornada e adicionais</h3><div className="form-grid">
          <Field label="Vigência a partir de"><input required type="month" value={contract.effective} onChange={e=>setContract({...contract,effective:e.target.value})}/></Field>
          <NumberField label="Salário mensal (R$)" value={contract.salary} onChange={v=>setContract({...contract,salary:v??0})}/>
          <NumberField label="Divisor mensal da jornada (horas)" value={contract.divisor} max={744} onChange={v=>setContract({...contract,divisor:v??0})}/>
          <Field label={`Anuênio automático · competência ${month}`}><output>{employee.admission?`${yearsAt(employee.admission,month)} ano(s) completo(s) × 1% = ${money(contract.salary*yearsAt(employee.admission,month)/100)}`:"Informe a admissão para calcular"}</output><small>Premissa de 1% ao ano da planilha; validar na convenção coletiva. Não é um adicional geral da CLT.</small></Field>
          <Field label="Recebe periculosidade?"><Select value={contract.danger?"yes":"no"} onValueChange={v=>setContract({...contract,danger:v==="yes",unhealthyRate:v==="yes"?0:contract.unhealthyRate})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="no">Não</SelectItem><SelectItem value="yes">Sim</SelectItem></SelectContent></Select><small>30% do salário-base: {money(contract.danger?contract.salary*.3:0)} por mês integral.</small></Field>
          {!contract.danger&&<Field label="Recebe insalubridade?"><Select value={contract.unhealthyRate?"yes":"no"} onValueChange={v=>setContract({...contract,unhealthyRate:v==="yes"?20:0})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="no">Não</SelectItem><SelectItem value="yes">Sim</SelectItem></SelectContent></Select></Field>}
          {contract.unhealthyRate>0&&<><Field label="Grau de insalubridade"><Select value={String(contract.unhealthyRate)} onValueChange={v=>setContract({...contract,unhealthyRate:Number(v)})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[10,20,40].map(v=><SelectItem key={v} value={String(v)}>{v}%</SelectItem>)}</SelectContent></Select></Field><NumberField label="Base de insalubridade validada (R$)" value={contract.unhealthyBase} onChange={v=>setContract({...contract,unhealthyBase:v??0})}/></>}
          <Field label="Recebe adicional noturno?"><Select value={contract.nightEligible?"yes":"no"} onValueChange={v=>setContract({...contract,nightEligible:v==="yes",nightRate:20})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="no">Não</SelectItem><SelectItem value="yes">Sim</SelectItem></SelectContent></Select><small>Regra urbana: 20% sobre a hora diurna, com hora reduzida de 52min30s. Informe as horas efetivamente trabalhadas no lançamento mensal.</small></Field>
          <Field label="Outro adicional fixo — descrição"><input value={contract.fixedName} placeholder="Ex.: gratificação de função" onChange={e=>setContract({...contract,fixedName:e.target.value})}/></Field><NumberField label="Outro adicional fixo — valor (R$)" value={contract.fixedValue} onChange={v=>setContract({...contract,fixedValue:v??0})}/>
        </div><Field label="Fundamento, laudo ou regra da convenção"><textarea value={contract.notes} onChange={e=>setContract({...contract,notes:e.target.value})}/></Field>
        <p className="note">Confirme o enquadramento dos adicionais, as bases e o divisor da jornada. Anuênio e adicionais convencionais dependem da regra aplicável. A opção de risco evita acumular automaticamente periculosidade e insalubridade. <a className="sources" href="https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452compilado.htm" target="_blank" rel="noreferrer">Consultar CLT</a></p>
        {employees.some(p=>p.id===employee.id)&&<details><summary>Vigências registradas</summary>{employee.contracts.map(c=><div className="history-row" key={c.effective}><span>{c.effective} · {money(c.salary)} · divisor {c.divisor}</span><button type="button" className="secondary" onClick={()=>setContract(structuredClone(c))}>Consultar / editar</button></div>)}</details>}
        <Field label="Motivo do cadastro ou alteração"><textarea required minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></Field><div className="dialog-actions"><button className="secondary" type="button" disabled={saving} onClick={()=>setEmployee(null)}>Cancelar</button><button className="primary" disabled={saving}>{saving?'Salvando...':'Salvar colaborador'}</button></div>
      </form>}
    </DialogContent></Dialog>
    <Dialog open={!!draft} onOpenChange={open=>{if(!open&&!saving)setDraft(null)}}><DialogContent className="entry-dialog"><DialogTitle>Lançamento mensal · {draft?.employee}</DialogTitle><DialogDescription>{draft?.month} — informe apenas as ocorrências e confira as bases desta competência.</DialogDescription>
      {draft&&<form onSubmit={e=>{e.preventDefault();persist({...state,entries:state.entries.some(r=>r.id===draft.id)?state.entries.map(r=>r.id===draft.id?draft:r):[...state.entries,draft]},reason,()=>{setDraft(null);setView('monthly')});}}>
        <div className="contract-strip"><span>Salário: <strong>{money(draft.salary)}</strong></span><span>Admissão: {draft.admission}</span><span>Contrato: {draft.monthly?.contractEffective??'Registro anterior'}</span></div>
        <p className="note">O contrato foi copiado para esta competência. Alterações na ficha não modificam lançamentos já salvos.</p>
        {draft.employeeId&&<button type="button" className="secondary" onClick={()=>{const person=employees.find(p=>p.id===draft.employeeId);if(!person)return;try{const renewed=entryFor(person,draft.month);setDraft({...draft,employee:renewed.employee,admission:renewed.admission,salary:renewed.salary,danger:renewed.danger,annuityRate:renewed.annuityRate,monthly:{...renewed.monthly!,hours50:draft.monthly?.hours50??0,hours100:draft.monthly?.hours100??0,nightHours:renewed.monthly?.nightEligible?(draft.monthly?.nightHours??0)*(draft.monthly?.nightClockHours?1:52.5/60):0,commission:draft.monthly?.commission??0,advance:draft.monthly?.advance??0,holidays:draft.monthly?.holidays??'',calendarConfirmed:false},inssBase:null,irrf:null,confirmed:false});toast.success('Contrato reaplicado nesta edição. Confira as bases e salve com justificativa.');}catch(e:any){toast.error(e.message);}}}>Reaplicar contrato vigente a este lançamento</button>}
        <h3>Ocorrências e remuneração variável</h3><div className="form-grid">
          {draft.monthly?<>{monthlyField('hours50','Horas extras com adicional de 50% (quantidade)',744)}{monthlyField('hours100','Horas extras com adicional de 100% (quantidade)',744)}{draft.monthly.nightEligible!==false&&monthlyField('nightHours',draft.monthly.nightClockHours?'Horas efetivas entre 22h e 5h (sem intervalos)':'Horas noturnas já convertidas — registro anterior',744)}{monthlyField('commission','Comissões (R$)')}{monthlyField('hourlyBase','Base remuneratória da hora (R$)')}{monthlyField('divisor','Divisor mensal da jornada',744)}</>:<>{entryField('extra50','H.E. 50% — valor legado (R$)')}{entryField('extra100','H.E. 100% — valor legado (R$)')}</>}
          {entryField('bonus','Bonificação do mês (R$)')}
        </div><p className="note">Horas extras = base da hora ÷ divisor × quantidade × 1,5 ou 2. Nos novos lançamentos, a conversão noturna é automática: 7 horas efetivas = 8 horas reduzidas. Use horas decimais (1h30 = 1,5), sem intervalos. Registros anteriores conservam a unidade indicada no campo. Prorrogações, outras categorias e horas extras noturnas exigem conferência específica. Não some as mesmas horas duas vezes.</p>
        <div className="contract-strip"><span>Anuênio automático: {money(calculated?.annuity??0)}</span><span>Periculosidade: {money(calculated?.danger??0)}</span><span>Adicional noturno: {money(calculated?.night??0)} · {(calculated?.nightReducedHours??0).toFixed(2)} horas reduzidas</span></div><h3>Calendário e DSR</h3>{draft.monthly&&<><button type="button" className="secondary" onClick={()=>{const holidays=holidayDates(state,draft.month);setDraft({...draft,...calendar(draft.month,holidays),monthly:{...draft.monthly!,holidays,calendarConfirmed:false},confirmed:false});toast.success('Calendário anual aplicado. Confira e salve o lançamento.');}}>Aplicar feriados do cadastro anual</button><p className="note">Novos lançamentos recebem os feriados cadastrados automaticamente. Este botão substitui as datas desta edição pelas do calendário anual.</p><Field label="Feriados da competência (AAAA-MM-DD, separados por vírgula)"><input value={draft.monthly.holidays} onChange={e=>setMonthly('holidays',e.target.value)}/></Field><button type="button" className="secondary" onClick={()=>{const dates=draft.monthly!.holidays.split(/[\s,;]+/).filter(Boolean);if(dates.some(d=>!/^\d{4}-\d{2}-\d{2}$/.test(d)||!d.startsWith(draft.month)||Number.isNaN(Date.parse(d))||new Date(d).toISOString().slice(0,10)!==d)){toast.error('Informe datas válidas dentro da competência.');return;}setDraft({...draft,...calendar(draft.month,draft.monthly!.holidays),monthly:{...draft.monthly!,calendarConfirmed:false},confirmed:false});}}>Contar domingos e feriados</button><p className="note">A contagem considera sábado como dia útil e evita feriado duplicado com domingo. Ajuste os números conforme a jornada e a convenção.</p></>}
        <div className="form-grid">{entryField('workDays','Dias úteis para DSR')}{entryField('restDays','Repousos e feriados para DSR')}</div>{draft.monthly&&<label className="check"><Checkbox checked={draft.monthly.calendarConfirmed} onCheckedChange={v=>setMonthly('calendarConfirmed',v===true)}/>Conferi o calendário de {state.city}/{state.uf} e a jornada.</label>}
        <h3>Descontos e bases de contribuição</h3><div className="form-grid">{entryField('absenceDiscount','Desconto de faltas / perda de DSR (R$)')}{entryField('otherDiscount','Outros descontos (R$)')}{monthlyField('advance','Adiantamento a descontar (R$)')}{entryField('inssBase','Base de INSS confirmada (R$)',true)}{entryField('irrf','IRRF apurado (R$)',true)}{entryField('paid','Valor efetivamente pago (R$)',true)}</div>
        <p className="note">Prévia da base de INSS: {money(calculated?.base??0)}. Confirme as incidências de bonificações, adicionais e comissões. IRRF e base de INSS em branco ficam pendentes; informe zero quando realmente não houver desconto. Faltas são informadas em reais após apuração.</p>
        <label className="check"><Checkbox checked={draft.confirmed} onCheckedChange={v=>setEntry('confirmed',v===true)}/>Conferi os dados, adicionais, incidências e descontos.</label>
        <Field label="Justificativa do lançamento ou correção"><textarea required minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></Field>
        <div className="dialog-actions"><button className="secondary" type="button" disabled={saving} onClick={()=>setDraft(null)}>Cancelar</button><button className="primary" disabled={saving}>{saving?'Salvando...':'Salvar lançamento'}</button></div>
      </form>}
    </DialogContent></Dialog>
    <Dialog open={!!detail} onOpenChange={open=>{if(!open)setDetail(null)}}><DialogContent className="standard-dialog"><DialogTitle>Memória de cálculo · {detail?.employee}</DialogTitle><DialogDescription>{detail?.month} — resultados dos lançamentos salvos.</DialogDescription>{detail&&<ResultDetail entry={detail} convention={state.convention}/>}</DialogContent></Dialog>
  </section>;
}
function ResultDetail({entry:e,convention}:{entry:Entry;convention:string}){const c=calculate(e,convention);return <><div className="memory">{[['Salário',e.salary],['Periculosidade',c.danger],['Insalubridade',c.unhealthy],['Anuênio',c.annuity],[e.monthly?.fixedName||'Outros adicionais fixos',c.fixed],['Adicional noturno',c.night],['Horas extras 50%',c.extra50],['Horas extras 100%',c.extra100],['DSR sobre horas extras',c.dsr],['Bonificação',e.bonus],['Comissões',c.commission],['Total de adicionais e verbas variáveis',c.additionalTotal],['Bruto',c.gross],['Base INSS',c.base],['INSS',c.contribution?.total??null],['IRRF informado',e.irrf],['Faltas / perda de DSR',e.absenceDiscount],['Adiantamento',c.advance],['Outros descontos',e.otherDiscount],['Líquido preliminar',c.net],['Valor pago',e.paid],['Diferença a conferir',c.difference]].map(([label,value])=><div className={`memory-line ${label==='Líquido preliminar'?'memory-total memory-total-net':['Total de adicionais e verbas variáveis','Bruto'].includes(String(label))?'memory-total':''}`} key={String(label)}><span>{label}</span><strong>{value===null?'Não informado':money(Number(value))}</strong></div>)}</div><p className="note">Hora-base: {money(c.hourly)}. DSR = total de horas extras em reais ÷ {e.workDays} dias úteis × {e.restDays} repousos/feriados. Não inclui reflexos de comissões ou de outras rubricas no DSR. Motor {c.engine}.</p>{c.warnings.length>0&&<ul className="warning-list">{c.warnings.map(w=><li key={w}>{w}</li>)}</ul>}<p className="note">Diferença = líquido preliminar − valor pago. Os resultados pendentes precisam da conferência do contador antes do fechamento.</p></>}
